#!/bin/bash

alias gmail="firefox 'http://www.gmail.com'"
alias stack-overflow="firefox 'http://www.stackoverflow.com'"
alias gsearch="firefox -search"
alias ipython="ipython qtconsole --colors=Linux"
alias ipythonqt="ipython qtconsole --colors=Linux"
alias gipython="ipython qtconsole --colors=Linux"
alias s='screen'
alias dropbox='~/.dropbox-dist/dropboxd'
alias gedit='gedit'
alias esimpleutils='gvim ~/Dropbox/python/simpleutils/'
alias gitrm='git rm -r --cached'
alias work='cd ~/workspace'
alias apt='sudo aptitude'
